/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.5
 * Generated at: 2017-10-09 05:53:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    <script type=\"text/javascript\" src=\"js/jquery-3.2.1.min.js\"></script>\t\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\" integrity=\"sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4\" crossorigin=\"anonymous\"></script>\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js\" integrity=\"sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1\" crossorigin=\"anonymous\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.validate.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-flash-1.4.2/b-html5-1.4.2/r-2.2.0/datatables.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write("\t$().ready(function(){\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t$('#frEditForm').validate({\n");
      out.write("\t\t\trules:{\n");
      out.write("\t\t\t\tmName:\"required\",\n");
      out.write("\t\t\t\tmPhone:{\n");
      out.write("\t\t\t\t\trequired:true,\n");
      out.write("\t\t\t\t\tminlength:10,\n");
      out.write("\t\t\t\t\tmaxlength:10\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tmEmail:{\n");
      out.write("\t\t\t\t\trequired:true,\n");
      out.write("\t\t\t\t\temail:true\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tmAddress:\"required\",\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tmessages:{\n");
      out.write("\t\t\t\tmName:\"Enter Friend's name.\",\n");
      out.write("\t\t\t\tmPhone:{\n");
      out.write("\t\t\t\t\trequired:\"Enter phone Number.\",\n");
      out.write("\t\t\t\t\tminlength:\"Enter atleast 10 digit.\"\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tmEmail:{\n");
      out.write("\t\t\t\t\trequired:\"Enter Email.\",\n");
      out.write("\t\t\t\t\temail:\"Enter valid email.\"\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tmAddress:\"Enter Address.\"\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t/*\n");
      out.write("\t\t\n");
      out.write("\t\t$('#frEditForm').validate({\n");
      out.write("\t\t\trules:{\n");
      out.write("\t\t\t\tmName:\"required\",\n");
      out.write("\t\t\t\tmPhone:{\n");
      out.write("\t\t\t\t\trequired:true,\n");
      out.write("\t\t\t\t\tminlength:10,\n");
      out.write("\t\t\t\t\tmaxlength:10\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tmEmail:{\n");
      out.write("\t\t\t\t\trequired:true,\n");
      out.write("\t\t\t\t\temail:true\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tmAddress:\"required\",\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tmessages:{\n");
      out.write("\t\t\t\tmName:\"Enter Friend's name.\",\n");
      out.write("\t\t\t\tmPhone:{\n");
      out.write("\t\t\t\t\trequired:\"Enter phone Number.\",\n");
      out.write("\t\t\t\t\tminlength:\"Enter atleast 10 digit.\"\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tmEmail:{\n");
      out.write("\t\t\t\t\trequired:\"Enter Email.\",\n");
      out.write("\t\t\t\t\temail:\"Enter valid email.\"\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tmAddress:\"Enter Address.\"\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t*/\n");
      out.write("\t\tviewall();\t\n");
      out.write("\t});\t\n");
      out.write("\t\n");
      out.write("\tfunction importFr(){\n");
      out.write("\t\tvar formData = new FormData();\n");
      out.write("\t\tjQuery.each(jQuery('#file1')[0].files, function(i, file) {\n");
      out.write("\t\t    formData.append('file-'+i, file);\n");
      out.write("\t\t});\n");
      out.write("\t\tif ($('#file1').get(0).files.length === 0) {\n");
      out.write("\t\t    console.log(\"No files selected.\");\n");
      out.write("\t\t    //alert(\"No files selected.\");\n");
      out.write("\t\t    $('#msg').show();\n");
      out.write("\t\t    $('#successMsg').text(\"No File Selected\");\n");
      out.write("         ev.preventDefault();\n");
      out.write("\t\t}\n");
      out.write("\t\telse {\n");
      out.write("         $(this).unbind('submit').submit()\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t        url: \"../Import\",\n");
      out.write("\t        type: 'POST',\n");
      out.write("\t        data: formData,\n");
      out.write("\t        async: false,\n");
      out.write("\t        success: function (data) {\n");
      out.write("\t        \t$('#frTable').DataTable().ajax.reload();\n");
      out.write("\t        \t\n");
      out.write("\t        \tif(data==\"only xml file supported\"){\n");
      out.write("\t        \t\t//alert(data)\n");
      out.write("\t        \t\t$('#msg').show();\n");
      out.write("\t\t        \t$('#msg').text(\"only xml file supported\");\n");
      out.write("\t\t        \t$('#msg').delay(1000).fadeOut(1000);\n");
      out.write("\t        \t}\n");
      out.write("\t        \t\telse{\n");
      out.write("\t        \t\t\t$('#msg').show();\n");
      out.write("\t\t        \tdocument.getElementById(\"msg\").innerHTML=data+\" Records inserted\";\n");
      out.write("\t\t        \t$('#msg').delay(1000).fadeOut(1000);\n");
      out.write("\t            //alert(data+\" Records inserted\")\n");
      out.write("\t        \t\t}\n");
      out.write("\t        },\n");
      out.write("\t        cache: false,\n");
      out.write("\t        contentType: false,\n");
      out.write("\t        processData: false\n");
      out.write("\t    });\n");
      out.write("\t    return false;\n");
      out.write("\t\t}\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction addFr(){\n");
      out.write("\t\tvar gender = document.querySelector('input[name = \"mGender\"]:checked').value;\t\t\n");
      out.write("\t\t$.post(\"../CRUD\", {\n");
      out.write("\t\t\tname : $(\"#mName\").val(),\n");
      out.write("\t\t\tphone : $(\"#mPhone\").val(),\n");
      out.write("\t\t\temail : $(\"#mEmail\").val(),\n");
      out.write("\t\t\taddress : $(\"#mAddress\").val(),\t\t\t\t\n");
      out.write("\t\t\tgender : gender,\n");
      out.write("\t\t\tmstatus : $(\"#mStatus\").val(),\n");
      out.write("\t\t\tdob : $(\"#mDob\").val(),\n");
      out.write("\t\t\tact : $(\"#addact\").val()\n");
      out.write("\t\t}, doAdd);\n");
      out.write("\t}\n");
      out.write("\tfunction doAdd(reponse){\n");
      out.write("\t\t$('#myModal').modal('hide');\n");
      out.write("\t\tclearFr();\n");
      out.write("\t\t$('#frTable').DataTable().ajax.reload();\n");
      out.write("\t}\n");
      out.write("\t\t\n");
      out.write("\t function clearFr()\n");
      out.write("\t    {\n");
      out.write("\t        $(\"#mId\").val(\"\");\n");
      out.write("\t        $(\"#mName\").val(\"\");\n");
      out.write("\t        $(\"#mPhone\").val(\"\");\n");
      out.write("\t        $(\"#mEmail\").val(\"\");\n");
      out.write("\t        $(\"#mAddress\").val(\"\");\n");
      out.write("\t        //$('input[name=mGender]').val(\"\");\n");
      out.write("\t        //$(\"#mGender\").val(\"\");\n");
      out.write("\t        $(\"#mStatus\").val(\"\");\n");
      out.write("\t        $(\"#mDob\").val(\"\");\n");
      out.write("\t        \n");
      out.write("\t    }\n");
      out.write("\t function addMd(){\n");
      out.write("\t\t clearFr();\n");
      out.write("\t\t $(\"#showBtn\").html(\"\");\n");
      out.write("\t\t var str='<input type=\"button\" style=\"float: right;\" onclick=\"addFr()\" class=\"btn btn-primary\" id=\"btnAdd\" value=\"Add Friend\">'\n");
      out.write("\t\t\t $(\"#showBtn\").html(str);\n");
      out.write("\t }\n");
      out.write("\t\n");
      out.write("\tfunction viewall() {\t\t\n");
      out.write("\t\t\tvar act = $(\"#viewallact\").val();\t\t\n");
      out.write("\t\t\t$('#frTable').DataTable({\n");
      out.write("\t\t\t\t\t\t\t\tresponsive: true,\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\tdom: 'Bfrtip',\n");
      out.write("        \t\t\t\t\t\tbuttons: [\n");
      out.write("        \t\t\t\t\t\t          \t{\n");
      out.write("        \t\t\t\t\t\t         \textend: 'excel',\n");
      out.write("        \t\t\t\t\t\t          \ttitle : null,\n");
      out.write("        \t\t\t\t\t\t          \texportOptions:{\n");
      out.write("        \t\t\t\t\t\t        \tcolumns : [1,2,3,4,5,6],\n");
      out.write("        \t\t\t\t\t\t          \t}       \t\t\t\t\t\t          \n");
      out.write("        \t\t\t\t\t\t          \t}       \t\t\t\t\t\t                  \t\t\t\t\t\t               \t\t\t\t\t\t          \n");
      out.write("        \t\t\t\t\t\t          ],        \t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\tajax : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : \"../CRUD\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata : {'act' : act},\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdataSrc : 'data'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\tcolumns : [{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\torderable: false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsortable:false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata : \"id\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'render' : function(data, type,full, meta) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn '<input type=\"checkbox\" id=\"options\" name=\"options\" value=\"'+data+'\">';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{data : \"name\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{data : \"phone\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{data : \"email\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{data : \"address\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{data : \"gender\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{data : \"mstatus\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{data : \"dob\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{orderable: false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t sortable:false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t data : \"id\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    \"render\" : function(data, type,row, meta) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn '<a  href=\"javascript:showModal('+ data +')\">Edit</a>';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t }\n");
      out.write("\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t});\n");
      out.write("\t\t                 }\n");
      out.write("\n");
      out.write("\t\tfunction showModal(i) {\n");
      out.write("\t\t\t$(\"#myModal\").modal('show');\t\n");
      out.write("\t\t\t$(\"#showBtn\").html(\"\");\n");
      out.write("\t\t\tvar str = '<button type=\"button\" id=\"updatebtn\" class=\"btn btn-primary\" onClick=\"updateFr()\">Update Friend</button>';\n");
      out.write("\t        $(\"#showBtn\").html(str);\n");
      out.write("\t        \n");
      out.write("\t\t\t$.get('../CRUD', {'frId' : i,'act' : $(\"#showact\").val()}, function(data) {\n");
      out.write("\t\t\t\tif (data) {\n");
      out.write("\t\t\t\t\tmyObj = JSON.parse(data);\n");
      out.write("\t\t\t\t\tdocument.getElementById('mId').value = i;\n");
      out.write("\t\t\t\t\tvar gender = myObj.gender;\n");
      out.write("\t\t\t\t\tvar mstatus = myObj.mstatus;\n");
      out.write("\t\t\t\t\t$('#mName').val(myObj.name);\n");
      out.write("\t\t\t\t\t$('#mPhone').val(myObj.phone);\n");
      out.write("\t\t\t\t\t$('#mEmail').val(myObj.email);\n");
      out.write("\t\t\t\t\t$('#mAddress').val(myObj.address);\n");
      out.write("\t\t\t\t\tif (gender == \"male\") {\n");
      out.write("\t\t\t\t\t\t$('#mGenderM').prop('checked', true);\n");
      out.write("\t\t\t\t\t} else if (gender == \"female\") {\n");
      out.write("\t\t\t\t\t\t$('#mGenderF').prop('checked', true);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tif (mstatus == \"unmarried\")\n");
      out.write("\t\t\t\t\t\t$('.mStatus option:eq(2)').prop('selected', true)\n");
      out.write("\t\t\t\t\telse if (mstatus == \"married\")\n");
      out.write("\t\t\t\t\t\t$('.mStatus option:eq(1)').prop('selected', true)\n");
      out.write("\t\t\t\t\t$('#mDob').val(myObj.dob);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction updateFr() {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar gender = document.querySelector('input[name = \"mGender\"]:checked').value;\n");
      out.write("\t\t\t$.post(\"../CRUD\", {\n");
      out.write("\t\t\t\tfrId : $(\"#mId\").val(),\n");
      out.write("\t\t\t\tname : $(\"#mName\").val(),\n");
      out.write("\t\t\t\tphone : $(\"#mPhone\").val(),\n");
      out.write("\t\t\t\temail : $(\"#mEmail\").val(),\n");
      out.write("\t\t\t\taddress : $(\"#mAddress\").val(),\t\t\t\t\t\t\n");
      out.write("\t\t\t\tgender : gender,\n");
      out.write("\t\t\t\tmstatus : $(\"#mStatus\").val(),\n");
      out.write("\t\t\t\tdob : $(\"#mDob\").val(),\n");
      out.write("\t\t\t\tact : $(\"#updateact\").val()\n");
      out.write("\t\t\t}, doUpdate);\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction doUpdate(response) {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(response){\n");
      out.write("\t\t\t$('#myModal').modal('hide');\n");
      out.write("\t\t\t$('#frTable').DataTable().ajax.reload();\t\n");
      out.write("\t\t\t$(\"#showBtn\").html(\"\");\n");
      out.write("            var str = '<button type=\"button\" id=\"addbtn\" class=\"btn btn-primary\" onclick=\"addFr()\">Add Friend</button>';\n");
      out.write("            $(\"#showBtn\").html(str);\n");
      out.write("            clearFr();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction deleteFr() {\n");
      out.write("\n");
      out.write("\t\t\t\tvar checked1=[]\n");
      out.write("\t\t\t\t$(\"input[name='options']:checked\").each(function (){\n");
      out.write("\t\t\t\t    checked1.push(parseInt($(this).val()));\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\tvar myObj = JSON.stringify(checked1);\t\t\t\t\n");
      out.write("\t\t\t\t$.post(\"../CRUD\", {\n");
      out.write("\t\t\t\t\tfrIdDl : myObj,\n");
      out.write("\t\t\t\t\tact : $(\"#deleteact\").val()\n");
      out.write("\t\t\t\t}, doDelete);\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction doDelete(response) {\n");
      out.write("\t\t\t$('#frTable').DataTable().ajax.reload();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
