/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.5
 * Generated at: 2017-10-09 06:11:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Kaldin.emp.dbConnection.DbConnection;
import java.sql.*;

public final class homePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Kaldin.emp.dbConnection.DbConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css\" integrity=\"sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M\" crossorigin=\"anonymous\">\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-flash-1.4.2/b-html5-1.4.2/r-2.2.0/datatables.min.css\"/>\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write(" ");

        HttpSession ses=request.getSession();
        String email=(String)ses.getAttribute("email");
        String uname=(String)ses.getAttribute("uname");
        String empId=(String)ses.getAttribute("empId");
        
        
        if(email==null||"".equals(email))
        {
        	
      out.write("\n");
      out.write("        \t");
      if (true) {
        _jspx_page_context.forward("loginPage.jsp");
        return;
      }
      out.write("\n");
      out.write("        \t");
 
        }
        
      out.write("\n");
      out.write("            <input type=\"hidden\" id=\"viewallact\" name=\"viewallact\" value=\"viewall\"/>\n");
      out.write("    <input type=\"hidden\" id=\"addact\" name=\"addact\" value=\"add\"/>\n");
      out.write("    <input type=\"hidden\" id=\"deleteact\" name=\"deleteact\" value=\"delete\"/>\n");
      out.write("    <input type=\"hidden\" id=\"showact\" name=\"showact\" value=\"show\"/>\n");
      out.write("    <input type=\"hidden\" id=\"updateact\" name=\"updateact\" value=\"update\"/>\n");
      out.write("        \n");
      out.write("    <nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-dark\">\n");
      out.write("      <a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/Home\">Navbar</a>\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExampleDefault\" aria-controls=\"navbarsExampleDefault\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("      </button>\n");
      out.write("\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarsExampleDefault\">\n");
      out.write("        <ul class=\"navbar-nav mr-auto\">\n");
      out.write("          <li class=\"nav-item active\">\n");
      out.write("            <a class=\"nav-link\" href=\"#\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"#\">Link</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link disabled\" href=\"#\">Disabled</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"dropdown01\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Dropdown</a>\n");
      out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"dropdown01\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">Action</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">Another action</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">Something else here</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("          <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("          <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("          <a class=\"btn btn-outline-success my-2 my-sm-0\" href=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" type=\"submit\"><span class=\"glyphicon glyphicon-log-out\" ></span>Log Out</a>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Main jumbotron for a primary marketing message or call to action -->\n");
      out.write("    <div class=\"jumbotron\">\n");
      out.write("      <div class=\"fw-container\">\n");
      out.write("        <h6 class=\"display-5\">Welcome \n");
      out.write("       \n");
      out.write("    \t\t\t");
      out.print(uname );
      out.write(" !<input type=\"hidden\" id=\"empEmail\" value=\"");
      out.print(email);
      out.write("\"></h6>\n");
      out.write("<br>        \n");
      out.write("        <div class=\"fw-container\" >\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div id=\"msg\" style=\"display:none;\" class=\"alert alert-success\" role=\"alert\" >\n");
      out.write("\t\t\t\t\t\t<strong><p id=\"successMsg\"></p></strong> \n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t<form id=\"importForm\">\n");
      out.write("\t\t\t\t<div class=\"form-group\">\t\t\t\t\n");
      out.write("\t\t\t\t\t<label for=\"exampleInputFile\">Add Friends using File</label> \n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control-file\" id=\"file1\" name=\"file1\" aria-describedby=\"fileHelp\"> \t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<button type=\"button\" onclick=\"importFr()\" class=\"btn btn-primary\">Submit</button>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div> \t\t\t\n");
      out.write("\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t<input type=\"button\" style=\"float: right;\" data-toggle=\"modal\" data-target=\"#myModal\" onclick=\"addMd()\" class=\"btn btn-primary\" id=\"btnAdd\" value=\"Add Friend\">\n");
      out.write("\t\t\t</div> \n");
      out.write("\t\t</div>    \t\t\n");
      out.write("\t</div>                 \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <div class=\"fw-container\">\n");
      out.write("    \n");
      out.write("\t\t<button type=\"button\"  onclick=\"deleteFr()\">\n");
      out.write("\t\t  <i class=\"fa fa-trash\" aria-hidden=\"true\"> Delete Selected</i>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t<a href=\"../Export\"><button type=\"button\"  >\n");
      out.write("\t\t  <i class=\"fa fa-file-excel-o\" aria-hidden=\"true\"> Export All</i>\n");
      out.write("\t\t</button></a>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Modal -->\n");
      out.write("\t\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\t\t\taria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLabel\">Edit Friend's Detail</h5>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t<form id=\"frEditForm\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\"  id=\"mId\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"recipient-name\" class=\"form-control-label\">Name:</label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  id=\"mName\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"recipient-name\" class=\"form-control-label\">Phone:</label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"tel\" class=\"form-control\" id=\"mPhone\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"recipient-name\" class=\"form-control-label\">Email:</label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"mEmail\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"recipient-name\" class=\"form-control-label\">Address:</label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"mAddress\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4\">\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"recipient-name\" class=\"form-control-label\">Gender:</label>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t      <span class=\"input-group-addon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t        <input type=\"radio\" aria-label=\"Checkbox for following text input\" name=\"mGender\" id=\"mGenderM\" value=\"male\">Male\n");
      out.write("\t\t\t\t\t\t\t\t\t      </span>\t\t\t\t\t\t\t\t\t      \n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t      <span class=\"input-group-addon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t        <input type=\"radio\" aria-label=\"Radio button for following text input\" name=\"mGender\" id=\"mGenderF\" value=\"female\">Female\n");
      out.write("\t\t\t\t\t\t\t\t\t      </span>\t\t\t\t\t\t\t\t\t      \n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"recipient-name\" class=\"form-control-label\">Marital\n");
      out.write("\t\t\t\t\t\t\t\t\tStatus:</label><div class=\"mStatus\"> <select id=\"mStatus\" name=\"mStatus\" class=\"form-control\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected>Choose...</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"married\">Married</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"unmarried\">Unmarried</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"recipient-name\" class=\"form-control-label\">Date\n");
      out.write("\t\t\t\t\t\t\t\t\tof Birth:</label> <input type=\"date\" class=\"form-control\" id=\"mDob\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"2011-08-19\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\t\n");
      out.write("\t\t\t\t\t<div id=\"showBtn\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"frSubmit\" onclick=\"addFr()\" class=\"btn btn-primary\">Add\n");
      out.write("\t\t\t\t\t\t\t\tFriend\n");
      out.write("\t\t\t\t\t\t\t</button>\t\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Example row of columns -->\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t<div style=\"text-align:center;\"><h3>Friend's Detail </h3></div>\n");
      out.write("\t\t\t\t<table id=\"frTable\" class=\"display\">\n");
      out.write("\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<th>Delete</th>\n");
      out.write("\t\t\t\t\t\t\t<th>name</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Phone</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Email</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Address</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Gender</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Marital Status</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Date of Birth</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Actions</th>\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</thead>\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</table>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\t\t\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<hr>\n");
      out.write("      <footer>\n");
      out.write("        <p>&copy; Company 2017</p>\n");
      out.write("      </footer>\n");
      out.write("    </div> <!-- /container -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
