/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.5
 * Generated at: 2017-09-27 04:56:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container\" >\n");
      out.write("\t\t<div class=\"outer\">\n");
      out.write("\t\t\t<form id=\"regForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/Registration\" method=\"POST\">\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<label for=\"lblname\" class=\"col-sm-3 col-form-label\">Name</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"Name\"><span id=\"errName\" class=\"fa fa-user err\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<label for=\"lblphone\" class=\"col-sm-3 col-form-label\">Phone</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\" placeholder=\"Phone\" maxlength=\"10\"><span id=\"errPhone\" class=\"fa fa-phone err\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<label for=\"lblemail\" class=\"col-sm-3 col-form-label\">Email</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Email\"><span id=\"errEmail\" class=\" fa fa-envelope err\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<label for=\"lbladdress\" class=\"col-sm-3 col-form-label\">Address</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" placeholder=\"Address\"><span id=\"errAddress\" class=\"fa fa-map-marker err\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<label for=\"lblgender\" class=\"col-sm-3 col-form-label\">Gender</label>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check \">\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-check-label \"> <input\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-check-input\" type=\"radio\" name=\"gen\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"exampleRadios1\" value=\"male\" checked> Male\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check \">\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-check-label \"> <input\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-check-input\" type=\"radio\" name=\"gen\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"exampleRadios2\" value=\"female\"> Female\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<label for=\"lblphone\" class=\"col-sm-3 col-form-label\">Marital\n");
      out.write("\t\t\t\t\t\tStatus</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<select class=\"custom-select mb-2 mr-sm-2 mb-sm-0\"\n");
      out.write("\t\t\t\t\t\t\tid=\"maritalStatus\" name=\"maritalStatus\">\n");
      out.write("\t\t\t\t\t\t\t<option selected>Choose...</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"married\">Married</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"unmarried\">UnMarried</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<label for=\"example-date-input\" class=\"col-sm-3 col-form-label\">Date\n");
      out.write("\t\t\t\t\t\tOf Birth</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" type=\"date\" value=\"2011-08-19\"\n");
      out.write("\t\t\t\t\t\t\tid=\"dob\" name=\"dob\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<label for=\"example-date-input\" class=\"col-sm-3 col-form-label\">Skills</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox-inline\"><input type=\"checkbox\"\n");
      out.write("\t\t\t\t\t\t\tname=\"chk1\" class=\"chk1\" value=\"java\" checked>Java</label> <label\n");
      out.write("\t\t\t\t\t\t\tclass=\"checkbox-inline\"><input type=\"checkbox\"\n");
      out.write("\t\t\t\t\t\t\tname=\"chk1\" class=\"chk1\" value=\"DotNet\">DotNet</label> <label\n");
      out.write("\t\t\t\t\t\t\tclass=\"checkbox-inline\"><input type=\"checkbox\"\n");
      out.write("\t\t\t\t\t\t\tname=\"chk1\" class=\"chk1\" value=\"php\">Php</label>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<label for=\"lblname\" class=\"col-sm-3 col-form-label\">Password</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" placeholder=\"password\"><span id=\"errPass\" class=\"fa fa-user err\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t<div class=\"offset-sm-2 col-sm-12\">\n");
      out.write("\t\t\t\t\t\t<center>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" id=\"btnSubmit\" class=\"btn btn-primary\">&nbsp&nbsp&nbsp&nbsp\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><input type=\"submit\" class=\"btn btn-secondary\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"cancel\" value=\"Cancel\"></a>\n");
      out.write("\t\t\t\t\t\t</center>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.validate.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script>  \n");
      out.write("\t\t   $().ready(function() {\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t$(\"#regForm\").validate({\n");
      out.write("\t\t\t\t\trules: {\n");
      out.write("\t\t\t\t\t\tname: \"required\",\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tphone: {\n");
      out.write("\t\t\t\t\t\t\trequired: true,\n");
      out.write("\t\t\t\t\t\t\tminlength: 10,\n");
      out.write("\t\t\t\t\t\t\tmaxlength: 10\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t},\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\temail: {\n");
      out.write("\t\t\t\t\t\t\trequired: true,\n");
      out.write("\t\t\t\t\t\t\temail: true\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\taddress: \"required\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\tmessages: {\n");
      out.write("\t\t\t\t\t\tname: \"Please enter your name\",\n");
      out.write("\t\t\t\t\t\tphone: {\n");
      out.write("\t\t\t\t\t\t\trequired: \"Please enter a phone\",\n");
      out.write("\t\t\t\t\t\t\tminlength: \"Your phone number must consist of least 10 characters\"\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\temail: \"Please enter a valid email address\",\n");
      out.write("\t\t\t\t\t\taddress: \"Plese enter address\",\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$('.chk1').on('change', function() {\n");
      out.write("\t\t\t\t    $('.chk1').not(this).prop('checked', false);  \n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t   });\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
